name: example-wkflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -  name: Welcome Message
           run: echo "My first GitHub Action"

        -  name: list files
           run: ls 

        -  name: Read Readme
           run: cat README.md