name: example-wkflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -  name: Checkout
           uses: actions/checkout@v4.2.2
           
        -  name: List and Read files
           run: |
            echo "First Workflow"
            ls
            cat README.md

        # -  name: list files
        #    run: ls 

        # -  name: Read Readme
        #    run: cat README.md