name: example-wkflow
on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        -  name: Checkout
           uses: actions/checkout@v4.2.2
           
        # -  name: List and Read files
        #    run: |
        #     echo "First Workflow"
        #     ls
        #     cat README.md

        -  name: Install cowsay
           run: sudo apt-get install cowsay -y

        -  name: Generate ASCII
           run: cowsay -f dragon "I am dragon and will rain fire on you!" >> dragon.txt

        -  name: Test File Exists
           run: grep -i "dragon" dragon.txt

        -  name: Read File
           run: cat dragon.txt

        -  name: list repo files
           run: ls -ltra
           