name: Exploring variables and secrets

on: 
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        -  name: docker build
           env:
              CONTAINER_REGISTRY: docker.io
              DOCKER_USERNAME: fevans
              IMAGE_NAME: github-actions-nginx
           run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

        -  name: docker login
           env:
              DOCKER_PWD: somesecurepassword
              DOCKER_USERNAME: fevans
              IMAGE_NAME: github-actions-nginx
           run: echo docker login --username=$DOCKER_USERNAME --password:$DOCKER_PWD

        -  name: docker publish
           env:
              CONTAINER_REGISTRY: docker.io
              DOCKER_USERNAME: fevans
              IMAGE_NAME: github-actions-nginx
           run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMGAGE_NAME:latest

    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
        -  name: Docker run
           run: echo docker run -d -p 8080:80 docker.io/dockerUsername/imagename:latest