name: Exploring variables and secrets

on: 
    push
env:
    IMAGE_NAME: github-actions-nginx
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        -  name: docker build
          
              
           run: echo docker build -t ${{vars.DOCKER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

        -  name: docker login     
           run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password:${{secrets.DOCKER_PASSWORD}}

        -  name: docker publish
           run: echo docker push ${{vars.DOCKER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMGAGE_NAME:latest

    deploy:
        runs-on: ubuntu-latest
        needs: docker
        steps:
        -  name: Docker run
           run: echo docker run -d -p 8080:80 ${{vars.DOCKER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest